### ISSUE TITLE
Upgrade with snapshots does not take snapshots

### ISSUE THREAD

**Issue by haivala** [egara/buttermanager#26]
I'm using the new fast action button. The process does not do anything to the snapshots and I have to click on the take snapshots button. That process does not remove old snapshots. When does it check for the snapshot amount? I have now defined Snapshots to keep: 3 and There is 2 subvolumes with 6 snapshots.

**Comment by egara** [comment]
Hi @haivala and thank you very much for your feedback.

I'll take a look into this issue, thanks for reporting. What distro are you using? 

I'm trying to refactor the whole application in order to package it for Fedora, so when I finish this process I'll take a look to it. Meanwhile, you can check "Check updates at startup" within Settings tab and when ButterManager runs, it will check for updates and a new window will pop-up with several additional buttons. Then, click on "Upgrade with snapshots" button. This button should create the new snapshots, make the upgrades and remove the old ones. 

Best,

Eloy

**Comment by haivala** [comment]
I'm using Arch.

That's the thing. I don't want it to check the updates on startup as I already know that there is updates and what they are because I have other means to do that.. enabling that setting and using the other dialogue it works as expected.

**Comment by roypen** [comment]
Hi. I have the same "issue" on Fedora 33. It looks like "Upgrade System with snapshots" works the same way as "... without snapshots" button.

**Comment by egara** [comment]
Thak you guys @haivala and @roypen for reporting and confirming it. I'll take a look at it when I finished the refactoring process for packaging ButterManager for Fedora :)

**Comment by egara** [comment]
New version 2.3 is OUT and this bug is fixed! (I hope so ;P)

Thank you very much to all of you for your feedback.
