### ISSUE TITLE
Not very mobile friendly

### ISSUE THREAD

**Issue by Strit** [egara/buttermanager#29]
With the development of the PinePhone and other linux based phones, having btrfs snapshots seems like a great addition.

Sadly, this tool does not look or function well under a mobile interface yet.

Here's some screenshots to give a hint. ;) 

![Screenshot_20210328_150828](https://user-images.githubusercontent.com/6380959/112753847-a3941c00-8fd9-11eb-930e-0909d46c66d7.png)
![Screenshot_20210328_150844](https://user-images.githubusercontent.com/6380959/112753848-a42cb280-8fd9-11eb-920a-187617cdb1fb.png)

**Comment by egara** [comment]
Hi @Strit and thank you very much for your feedback.

You are absolutely right. ButterManager was created with only Desktop use in mind. That's why I ended up creating windows with fixed height and width. But it is fair. Pinephone and Linux phones are gaining attraction and I could take a look again into the original layout of the application in order to make it more friendly for these use cases.

I'm not very familiar with QT5 layouts and I suspect that I have to re-do all this part so if someone could help me with this would be awesome :)

Nevertheless, I'll take a look. It is amazing that ButterManager could be a very handy BTRFS tool in phones too!! I'll keep you inform.

Thanks again.

Eloy

**Comment by egara** [comment]
Hi @Strit 

I've been working on version 2.5.0 just released today and it includes some features that I hope can solve the problems you had running ButterManager on a PinePhone. If you have time, it would be awesome you could test it.

- All the windows layouts have been re-implemented. This means that all windows are resizable now and they should re-scale accordingly and dynamically.
- A new feature to define the base font size increment for the UI has been included in Settings.

Using those two new features, I think the application should be more usable in small screens and even in large 4K screens.

Best wishes,

Eloy

**Comment by Strit** [comment]
Awesome. I will check it out!
