### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by xi-pinmping** [egara/buttermanager#45]
Hi, I'm running into this using gksu on a new ArchLabs install. If I pass anything to after the argument, I get 
>ValueError: invalid literal for int() with base 10: ''

**Comment by egara** [comment]
Hi! Thanks for the feedback.

Question: Why are executing ButterManager with gksu? It is no needed. Just use the ButterManager desktop entry created during the installation process or, if you want to execute it from the command line, just type buttermanager.

It will ask for your password because it needs to execute some commands  via sudo underneath to operate and should run properly.

I hope this helps!

**Comment by xi-pinmping** [comment]
Because it didn't work without gksu either. I assumed it needed permissions due to the nature of the application so gave that a shot as well. Have tried via desktop menu and through terminal. I'm on wayland so sudoing programs isn't always effective.

**Comment by egara** [comment]
Hi @xi-pinmping 
I have reproduced the error. I think it has nothing to do with gksudo. Today I have installed ButterManager from AUR in Manjaro and this exception is thrown. Maybe is something related to the new version of Python, so I have to investigate on that.
Thank you very much for the feedback!

**Comment by egara** [comment]
The problem is related to the creation or migration of buttermanager.yaml which is the properties file with all the user's configuration. If you want to run ButterManager meanwhile, you can follow these steps:

    cd ~/.buttermanager
    nano buttermanager.yaml

Paste this content of buttermanager.yaml
```
aur_repository: 0
check_at_startup: 0
grub_btrfs: 1
path_to_consolidate_root_snapshot: '@'
save_log: 0
snap_packages: 0
subvolumes_dest:
subvolumes_orig:
subvolumes_prefix:
subvolumes_snapshots_to_keep:
```

**Important note**: You will have to check the line **path_to_consolidate_root_snapshot: '@'**. This is the name of the subvolume you use for root. In order to obtain it:

    cat /etc/fstab

And look for the **/** mounting point. In my case:

```
UUID=8DFC-213D                            /boot/efi      vfat    umask=0077 0 2
UUID=bbad1b9c-49dc-4405-9c90-b034005e673b /              btrfs   subvol=@,defaults,noatime,space_cache,autodefrag,compress=lzo 0 1
UUID=bbad1b9c-49dc-4405-9c90-b034005e673b /home          btrfs   subvol=@home,defaults,noatime,space_cache,autodefrag,compress=lzo 0 2
UUID=bbad1b9c-49dc-4405-9c90-b034005e673b /mnt/defvol     btrfs   subvol=/,rw,ssd,defaults,noatime,space_cache,autodefrag,compress=lzo 0 0
tmpfs                                     /tmp           tmpfs   defaults,noatime,mode=1777 0 0
```

As you can see, my root is mounted from @:
**UUID=bbad1b9c-49dc-4405-9c90-b034005e673b /              btrfs   subvol=@,defaults,noatime,space_cache,autodefrag,compress=lzo 0 1**

That's why **path_to_consolidate_root_snapshot** property is '@'

If you have any doubt just tell me :)

Cheers.

**Comment by egara** [comment]
New version 2.4.3 is out with this issue fixed
