### ISSUE TITLE
Not working anymore after GRUB update 

### ISSUE THREAD

**Issue by haivala** [egara/buttermanager#47]
I'm getting this message: You have booted into an alternative snapshot. Do you want to consolidate it as your default

I'm not actually totally sure how I ended up with this problem. I'll try to explain.
first GRUB updated to new version and it did not work anymore (boot loop) so I booted up arch install usb and copied /boot/ from older snapshot to the active one. Then I was able to boot again. Then I loaded older snapshot to get everything like it was before the GRUB problem.

Next I had to run grub-install and grub-mkconfig to get the new version of GRUB working but now even if boot any snapshot or the active one buttermanager is always saying that message and consolidation does nothing.

Any tips how to fix this? I don't need my old snapshots.

**Comment by egara** [comment]
Hi @haivala 

I think this issue is not related to ButterManager (there are some issues reported in Arch [here](https://archlinux.org/news/grub-bootloader-upgrade-and-configuration-incompatibilities/) and in EndeavourOS [here](https://discovery.endeavouros.com/system-rescue/repair-a-non-booting-grub/2021/03/)) but maybe I can help you. Please, attach the output of these commands:

- sudo btrfs subvolume list /
- sudo cat /etc/fstab
- sudo mount
- cat ~/.buttermanager/buttermanager.yaml

Thanks! :)

**Comment by egara** [comment]
Ok, I'm going to detail the consolidation process in order to execute it by hand instead of using ButterManager. Doing this process the last active rootvol will be removed and instead, you will consolidate **/_snapshots/root-20220818-0** snapshot, which is the snapshot in wich the system is booting by default right now. This process won't be reversible.

1- Delete the active rootvol:

        sudo btrfs subvolume delete /mnt/defvol/_active/rootvol

2- Create a new active rootvol based on the snapshot in which the system has booted up:

        sudo btrfs subvolume snapshot /mnt/defvol/_snapshots/root-20220818-0 /mnt/defvol/_active/rootvol

3- Edit  /mnt/defvol/_active/rootvol and substitute **UUID=fa609ace-ea3a-4052-88cb-1c9669b70e2c	/** line with:

        UUID=fa609ace-ea3a-4052-88cb-1c9669b70e2c	/         	btrfs     	subvol=/_active/rootvol,rw,relatime,compress=lzo,ssd,discard,autodefrag,space_cache	0 0

4- Regenerate grub 

        sudo -S grub-mkconfig -o /boot/grub/grub.cfg

5- Restart the system. Now, if you execute **sudo mount** you should see this line:

        /dev/nvme0n1p2 on / type btrfs (rw,relatime,compress=lzo,ssd,discard,space_cache,autodefrag,subvolid=3756,subvol=/_active/rootvol)

And the execution of ButterManager should be normal again because it will detect that the system has booted into the active rootvol.

I hope this helps!

**Comment by haivala** [comment]
Thank you for this help! I'm sorry to say it did not work but it got me in the right track.

Thing was that I had run the `grub-install` when I had booted the snapshot and activated it. That modified the first `grub.cfg` entry to use the snapshot. What I needed to do was load the "active" snapshot and then I ran the `grub-install` again to modify the `grub.cfg` and then use it with `grub-mkconfig`.

Now everything is working like it should.
Lesson learnt: When you have loaded snapshot don't run `grub-install` and `fstab` entries did nothing.

Thank you again!

**Comment by egara** [comment]
Hi @haivala 

And thank you for sharing the solution. You are totally right. I was assuming that you were selecting **/_snapshots/root-20220818-0** in GRUB menu, so the "default" subvolume for GRUB would be still **_active/rootvol**.

I'm very happy that you could solve this problem. I close the issue then :)
