### ISSUE TITLE
Font size very small after upgrade to 2.5

### ISSUE THREAD

**Issue by lapineige** [egara/buttermanager#48]
After upgrading to version 2.5.0, the font size went from "normal" to "very very small" (just like on an HDPI screen).
I'm using a 15" laptop, Full HD definition.

Also I'm using a custom scaling in KDE settings (106,25%), just in case it could be related…

By the way : what's new in this version ? :)

**Comment by egara** [comment]
Hi @lapineige 

Now, you can set a font size increment on Settings tab because all the window layouts have been re-implemented and are re-scalable in order to make the application usable on larger resolutions (4K, etc) and small ones too (PinePhone for example). You can check all the [new features and improvements for version 2.5.0 here](https://github.com/egara/buttermanager#version-250).

Thanks for your feedback as always and I hope you enjoy version 2.5.0 :)
