### ISSUE TITLE
snap package not available

### ISSUE THREAD

**Issue by damian101** [egara/buttermanager#9]
`error: cannot open: "buttermanager_1.5_amd64.snap"` 
I also couldn't find ButterManager in the Snap Store.
I also tried to install it with the Python script but I had to edit the script in a lot of places to get it running without errors, but at the end it didn't install ButterManager anyway.
I tried this on openSUSE Tumbleweed. Installing it on Arch was super easy through the AUR.

**Comment by egara** [comment]
Hi @damian101 

Thank you very much for reporting this issue. The URL of the snap package located in my Google Drive was wrong (it was still pointing to version 1.4).

ButterManager is not in the Snap Store and it won't be :( This is the process I opened with Canonical to include it but finally it has not been possible https://forum.snapcraft.io/t/requesting-classic-confinement-for-buttermanager/9574

Basically, ButterManager needs classic confinement to work properly and because it uses the package manager of the underlying distribution, its inclusion to the Snap Store has been rejected. Nevertheless, I have built the snap package and stored in my Google Drive, and now it is available for installing it using the command line interface and it should work. For all the installation instructions please check the main page of the repository https://github.com/egara/buttermanager.

Arch is my main distribution and creating a package for AUR is very easy. That's why I could package ButterManager without any problem. For the rest of the distributions, snap package should work fine (I don't have time and experience for trying to package the application for the rest of the package managers, sorry)

Could you try it in openSUSE and give me your feedback now that the link for version 1.5 is fixed?

Again, thank you very much for reporting the bug and I hope ButterManager is useful for you!! :)

Best,

Eloy

**Comment by damian101** [comment]
@egara I tried it again on openSUSE and also Arch this time, but still the same.
`sudo snap install --beta core16` runs fine but I still get the same error when I run `sudo snap install buttermanager_1.5_amd64.snap --classic --dangerous`: `error: cannot open: "buttermanager_1.5_amd64.snap"`.

**Comment by egara** [comment]
Hi again @damian101 

I have installed the snap package without any issue in mi Arch system. I also have installed a fresh OpenSUSE Tumbleweed in a virtual machine and I haven't had any problem either. But I think what your problem could be. Yo need to execute the command

`sudo snap install buttermanager_1.5_amd64.snap --classic --dangerous`

from the directory where the snap was downloaded (for instance, I use Firefox and by default all the files downloaded go to **Downloads** directory). so first, cd into Downloads and then execute the command to install the snap package.

I have to say that the first time you run any application isntalled using a snap package takes a while to execute, so be patience. I had to wait 2 or 3 minutes until ButterManager was opened the first time. In my Arch installation it didn't take so long, so I think it is because openSUSE is in a virtual machine. After the firs run, the next time you open ButterManager should be as fast as any other application installed using zypper.

Please, could you try again and tell me your feedback?

Thank you very much!

Eloy

**Comment by damian101** [comment]
@egara Sorry, my fault. Apparently I always completely overread these two sentences:
"First, download the ButterManager snap here.
After this, ppen a terminal, go to the directory where the package is downloaded [...]"
I guess this was because of my belief that snap packages cannot be installed from local files (I read that several times).
Now the installation was quick and unproblematic.
Anyways, thank you for the quick support and thank you for creating ButterManager. :)

**Comment by egara** [comment]
@damian101 great news!!! 

Thank you for your words :)
